### ISSUE TITLE
Can no longer run a taskflow with zero workers

### ISSUE THREAD

**Issue by freehour** [cpp-taskflow/cpp-taskflow#128]
It is no longer possible to run a taskflow with zero workers, i.e. on the thread that calls
`executor.run(taskflow)`

I have a workload where I need to run some of my taskflows on a specific thread (the main thread). Prior to this commit https://github.com/cpp-taskflow/cpp-taskflow/commit/58d96bb3c9e3a0fad9174c03b1dbcbca567c7fd3 it was possible by passing the taskflow to an executor with zero workers, but now it throws an exception.
`if(_workers.size() == 0) {
    TF_THROW(Error::EXECUTOR, "no workers to execute the graph");
  }`

Is there another way to run a taskflow on a specific thread that I'm not aware of?

**Comment by tsung-wei-huang** [comment]
Hi @freehour , yes, starting from 2.3.0 (next release on the master branch) we will no longer support zero worker to run taskflow graphs. It was problematic to support this because zero worker basically means single thread with no need of task parallelism. Another reason is the performance. Zero worker requires a bit complicated specialized data structure to handle the task scheduling which is unnecessary. So we made the decision to kick out the case.
