### ISSUE TITLE
Support for “nameless” tasks?

### ISSUE THREAD

**Issue by elfring** [cpp-taskflow/cpp-taskflow#18]
It might be expected that [tasks can get a name](https://github.com/cpp-taskflow/cpp-taskflow/blob/3a523e8d71209a18e0cf969c73d5f155cc442282/README.md#task-api "Naming tasks") for this software.
* How do you think about to [identify tasks by any other means than the data type “`std::string`”](https://github.com/cpp-taskflow/cpp-taskflow/blob/9cf75aeec0fefa98e597b53169a615acec9e921e/taskflow.hpp#L318 "Storage for task names")?
* Can this class attribute be occasionally omitted generally?

**Comment by twhuang-uiuc** [comment]
By default task name is optional. If you do not specify the name, taskflow will dump its unique address value. Is this what you are asking about? As of yet, string is the best optional I could find.

**Comment by elfring** [comment]
* Do you distinguish an optional item from the empty string anyhow?
* Can this attribute be selected by a class template parameter?

**Comment by twhuang-uiuc** [comment]
What I meant was without giving it a name, the `dump` will use its address value. And I think `std::string` at this moment suffices because the main goal here is to get a human-readable string for debugging.

In fact, we thought about making it a template. This can actually be a good idea to make it more flexible. We will consider to include this in the next release based on users' feedbacks.

**Comment by elfring** [comment]
Your feedback sounds promising.

How do you think about a library configuration variant where the storage of empty strings can be avoided?
