### ISSUE TITLE
Add object/memory pool for task nodes

### ISSUE THREAD

**Issue by twhuang-uiuc** [cpp-taskflow/cpp-taskflow#34]
We are planning to add `object pool` or `memory pool` for task nodes to boost the performance. In large applications, frequently creating task nodes can introduce overhead due to the dynamic memory allocation.

**Comment by ForgeMistress** [comment]
I made a fork. If you'll have me, I could see what I can whip up for you guys if I'm able to find the time.

**Comment by twhuang-uiuc** [comment]
Hi @ForgeMistress , thanks for your interests! I have just invited you to the project organization. Please accept it if you are willing to join. 

We recently tried an object pool implementation but it didn't work out very well. Speed-up is almost zero. The idea is to recycle all the `Node` storage after `wait_for_all`. However, this also causes some lifetime issue because data may not be actually cleared due to the recycling. So, we currently leave this as an open problem, and it requires further research.

**Comment by ForgeMistress** [comment]
I've done some memory pooling experiments and found placement new and direct destructor invocation to be especially useful in the resetting department. Guessing the problem is a little more complex than that. Were there any specific gotchas that you guys ran into in your initial attempts?

**Comment by twhuang-uiuc** [comment]
Hi @ForgeMistress , yes we also tried placement new (with memory pool) on the first front and didn't find it faster either. Instead, our profiling highlighted the overhead of `std::function`, and this is why we than change the executor (threadpool) to be templated on a given closure. This can reduces one layer of virtual call and indeed we see a remarkable performance gain by doing so. Now, the only layer requiring this polymorphic function wrapper (`std::function`) is on the graph node, which stores the applications' callable objects.

We also found the scheduler can impact the performance a lot. The `SpeculativeThreadpool` has an optimization on making a linear task chain run on the same thread. This can save a lot especially on gaining ownership from the task queue of the threadpool which is protected by a `std::mutex`.

**Comment by ForgeMistress** [comment]
Makes sense. I can see why the performance gains from pooling itself would seem to be be negligible depending on how you're benchmarking it. However the advantage of pooling I found is not in raw speed within isolated tests, but in the long term operation of the application since memory fragmentation can be reduced to zero if done right. When taken outside of the test suite and put into a live application, a better allocation strategy can be a huge boon for performance in the application as a whole since the allocation locations are predictable and usually kept contiguous in memory. The thought I'm having now is to keep the Node instances in a contiguous memory container and instead use indices into that container everywhere else.

As far as the current node allocation strategy is concerned, please correct me if I'm wrong, but it seems as if the Node instances are being stored in a forward_list (the Graph alias at the top of the header) and the Node instance references and pointers originate from nodes in that list, correct? The use of a forward_list in and of itself invites the memory fragmentation issues and CPU cache misses that are usually expected of typical STL linked list implementations. With C++17, the ContiguousContainer spec was added and only 3 containers currently satisfy that: vector, basic_string, and array. Was there any functional reason behind the use of forward_list as opposed to a contiguous container?

**Comment by twhuang-uiuc** [comment]
Yes, you understanding about the architecture is correct. We use a Graph alias as a placeholder to replace it with a class that can implement its own object recycling and memory management. In fact, this is how we did the object pool and memory pool.

The rationale to use `forward_list` is that each node is neither copy-able nor movable due to an atomic variable. Also, use list-like data structures allows easy movement of the entire graph to an internal data storage such as topology when we dispatch a graph. We are in fact thinking into this direction of using `std::vector` but havn't come up with a nice solution.

**Comment by ForgeMistress** [comment]
Sounds like I have my marching orders then. I'll keep you posted if I come up with something. If somebody else comes along and sees this thread and wants to take a crack at it before I get a chance, I won't mind.

**Comment by twhuang-uiuc** [comment]
This is done now. Starting from v2.1.0, Cpp-Taskflow uses memory pool to save the allocation time for graph nodes.
