### ISSUE TITLE
Sharing threadpool between taskflows

### ISSUE THREAD

**Issue by vkhomenko** [cpp-taskflow/cpp-taskflow#39]
Is it possible to create several independent taskflows which share the same threadpool? The rational is that I would like to set the total number of threads to correspond to the number of h/w threads, but it's tricky with several taskflows.

**Comment by totalgee** [comment]
You are free to dispatch as many different sets (graphs) of tasks as you like on the Taskflow object.  These will all respect each set's inter-dependencies, and will all be scheduled on the same Threadpool.  For a simple example:

```c++
// A simple example to show sending multiple Taskflow graphs
// as separate batches (which will all run on the same taskpool).

#include <taskflow/taskflow.hpp>

std::mutex logMutex;

void dispatchBatch(tf::Taskflow& tf, int batch)
{
    auto taskMaker = [](std::string const& taskName, int batch) {
        return [=]() {
            // Simulate some work
            std::this_thread::sleep_for(std::chrono::milliseconds(57));
            {
                std::lock_guard<std::mutex> lock(logMutex);
                std::cout << "Batch " << batch << " - done task " << taskName << '\n';
            }
        };
    };
    auto[A, B, C, D] = tf.silent_emplace(
        taskMaker("A", batch),
        taskMaker("B", batch),
        taskMaker("C", batch),
        taskMaker("D", batch)
    );

    A.precede(B);  // B runs after A
    A.precede(C);  // C runs after A
    B.precede(D);  // D runs after B
    C.precede(D);  // D runs after C

    // Schedule this independent graph of tasks (so they start running)
    tf.dispatch();
}

int main()
{
    tf::Taskflow tf(std::thread::hardware_concurrency());
    for (auto batch = 0; batch < 4; ++batch) {
        dispatchBatch(tf, batch);
    }
    std::cout << "Tasks dispatched\n";
    tf.wait_for_all();
    std::cout << "All tasks finished\n";

    return 0;
}
```

Here is some example output from one run. Note that each batch's ordering (task A, followed by B or C in any order, followed by D) is respected, but tasks from any given batch can run at any time relative to other batches).

```txt
Tasks dispatched
Batch 2 - done task A
Batch 1 - done task A
Batch 0 - done task A
Batch 3 - done task A
Batch 2 - done task C
Batch 2 - done task B
Batch 1 - done task C
Batch 1 - done task B
Batch 0 - done task B
Batch 0 - done task C
Batch 3 - done task C
Batch 3 - done task B
Batch 2 - done task D
Batch 1 - done task D
Batch 0 - done task D
Batch 3 - done task D
All tasks finished
```

Of course, the task "batches" don't have to be all of the same kind, as they are in my example. They can obviously contain unrelated processing graphs.

Also, note that the Taskflow object itself is not multi-thread-safe, meaning it must be accessed from a single thread (unless you put in place protection). However, you're free to use it in different places in your program, to schedule and dispatch different work graphs that can overlap in time.

Does that help?

**Comment by totalgee** [comment]
Great!  And yes, I suppose using a singleton would be one way for an application to manage this.

By the way, I just added an example (PR #40 adds `examples/multiple_dispatch.cpp`) that illustrates my example above in a bit more detail.

**Comment by vkhomenko** [comment]
It would be nice to provide such a singleton - saving the user from the necessity to code it? Also, will remove the "Taskflow tf;" line of code in many programs.

**Comment by twhuang-uiuc** [comment]
@totalgee @vkhomenko  Thanks for this very helpful discussion. Yes, you can dispatch a graph as many times as you want by calling `dispatch` or `silent_dispatch`; the former returns a `future` object for you to `get` on completion, while the later doesn't. Calling `wait_for_all` will block until **all** taskflow graphs completes, including previously dispatched ones.

I am not quite sure having a singleton taskflow is a good choice. You can create one taskflow object that is shared in your applications. Taskflow allows you to create multiple graphs and dispatch graphs from time to time. Please correct me if I misunderstand your points.

**Comment by vkhomenko** [comment]
@twhuang-uiuc 
I'm very new to this library, so maybe misunderstood something. Let me repeat my argument:

1. Most applications don't need multiple threadpools, as this can easily lead to oversubscription and so degrade the performance. So only one global threadpool is needed.
2. A Taskflow object is essentially a wrapper for a threadpool, so there should be only one global object of type Taskflow.
3. This is exactly the situation when Singleton pattern is recommended.
4. The user should not be burdened with the task to implement this singleton - the library can provide the default one. (E.g. Taskflow class can have some static methods to control the default instance of Taskflow.)
5. If the user for some strange reason needs multiple Taskflow objects, this is still possible.

**Comment by ForgeMistress** [comment]
Per my comments in an email thread with @twhuang-uiuc 

> Honestly, the way I'd personally prefer to share the thread pool is to have the client application claim ownership over the pointer to the thread pool. So something like this is what I'd personally go for.

// added bonus, the end-user could also potentially define their own closure types since the Closure structure looks simple enough. would be an amazing feature for debugging since operator() could do more than just invoke the closure. debug output, issue detection, etc...
struct SomeEngineSystem
{
    eastl::shared_ptr<SpeculativeThreadpool<AppSpecificClosureOrDefault>> _threadpool;
    tf::TaskFlow<AppSpecificClosureOrDefault> _tf1;
    tf::TaskFlow<AppSpecificClosureOrDefault> _tf2;
    tf::TaskFlow<AppSpecificClosureOrDefault> _tf3;
    // getters/setters omitted.
};

SomeEngineSystem::SomeEngineSystem()
: _threadpool(NUM_THREADS)
, _tf1(_threadpool) // possibly holds a weak pointer to the threadpool so full ownership is retained by the application.
, _tf2(_threadpool)
, _tf3(_threadpool)
{}

SomeEngineSystem::~SomeEngineSystem()
{
    _tf1.wait_for_topologies();
    _tf2.wait_for_topologies();
    _tf3.wait_for_topologies();
    _threadpool = nullptr; // released, taskflows no longer have a threadpool.
}

An API like that would appeal to me way more since then I can more directly manage the lifetime of threads within my application. Reducing (or increasing) the number of worker threads could then be as simple as waiting for the topologies of all of the graphs to complete and then call a few functions to reduce/increase the number of worker threads (or if that's not possible, create an entirely new threadpool with the appropriate number of worker threads and give it to the taskflow graphs). I could see this being incredibly useful for things like mobile applications that would want to reduce memory usage when the app goes to the background but still want to remain responsive without needing to defer to an entirely different API, or when a laptop switches to battery and wants to reduce the number of worker threads to reduce the number of cores doing calculations at the cost of a perf hit.

// example use case that I could see in a theoretical mobile application, or even on a windows tablet since those seem to be gaining popularity nowadays.
void SomeEngineSystem::OnAppEnteredBackground()
{
    WaitForGraphs(); // wait on all of the graph topologies.
    _threadpool->SetWorkerCount(2); // keep 2 worker threads running while the program is in a low power state since it would be doing a lot less anyway. no point in keeping those extra worker threads spinning their wheels if they're going to be under-utilized.
}

void SomeEngineSystem::OnAppEnteredForeground()
{
    WaitForGraphs(); // wait on all of the graph topologies.
    _threadpool->SetWorkerCount(std::thread::hardware_concurrency()); // FULL POWAH!
}

Then again, I notice you guys use control vars to manage when threads run their processing loop, so something like that might not be needed. That and I'm not 100% sure on how much memory and processing power a thread on its own actually uses when waiting on one of those CVs, so it's up to you guys. This is just how my brain is processing this particular aspect of what could be possible with a separation like this. That and I'm not exactly the most brilliant mind in the world when it comes to threads, so it is indeed possible that I could be talking complete gibberish.

**Comment by twhuang-uiuc** [comment]
This is completed in both dev and master branches. Please refer to [Thread Management and Task Execution](https://github.com/cpp-taskflow/cpp-taskflow/blob/master/doc/advanced/thread.md) and the example [executor.cpp](https://github.com/cpp-taskflow/cpp-taskflow/blob/master/example/executor.cpp). Each taskflow object maintains a shared pointer to an executor and users can acquire an ownership to share with others. The code looks like the following:

```cpp
#define MAX_THREAD 4
#define MAX_TASKFLOW 100

std::list<tf::Taskflow> tfs;

auto executor = std::make_shared<tf::Taskflow::Executor>(MAX_THREAD);

for(size_t i=0; i<MAX_TASKFLOW; ++i) {
  assert(executor.use_count() == i + 1);
  auto& tf = tfs.emplace_back(executor);
}

// 100 taskflow objects running on the same set of threads (4 threads)
```
