### ISSUE TITLE
Undefined behaviour of per_thread_object_pool() on Windows in case of multi-DLL application architecture

### ISSUE THREAD

**Issue by bsviglo** [cpp-taskflow/cpp-taskflow#96]
Here is a call stack where we constantly allocated memory but never freed it (memory growing is pretty big couple of 100s of Mb per minute)
![image](https://user-images.githubusercontent.com/6697628/60871404-538c8900-a23b-11e9-89ff-bccf477d47d9.png)
I have graph (`tf::Taskflow`) with each task use inner parallelizm by using `tf::Subflow` and parallel_for.
One more thing, I recreate `tf::TaskFlow` every frame. Maybe it's not desired behaviour (you're using internal caching), but any way I think we should support this case also.
I'd like to be sure that whenever I delete `tf::TaskFlow` object I also delete all related internal allocated memory including caching.

**Update:** I'm using the latest master version, the same behaviour on 2.2.0 version

**Update:** I've changed my code that now I create `tf::TaskFlow` once and reuse it during entire program execution but I still observe lots of memory allocated by the provided above callstack

**Update:** I think a have an idea what is wrong. My application uses multi-DLL architecture, where I have main application and lots of DLL all of them uses cpp-taskflow. So I think that each DLL use own copy of cpp-taskflow (and `thread_local `variables) which may results in undefined behaviour or memory leak, but I'm not certain about this idea yet.

**Update:** Link on MSDN with thread_local storage and multi-DLL https://developercommunity.visualstudio.com/content/problem/124121/thread-local-variables-fail-to-be-initialized-when.html

**Comment by clin99** [comment]
Hi @bsviglo , thanks for pointing out this issue. Yes, `tf::Taskflow` has an object pool to cache the memory for later use when a graph is destroyed. As a result, it would be memory efficient to create new graphs after old graphs are destroyed.  Even though this still causes memory to be kept when all graphs are destroyed, the memory will eventually be released in the end of the program. So there shouldn't be any memory leak. I am not sure whether your case is due to the thread_local storage and DLL on Windows platform or not. Do you get the memory leak reported from a memory profiler such as Valgrind or do you just measure the memory usage of the program ?

Thanks.

**Comment by tsung-wei-huang** [comment]
@bsviglo  it would be even better if you can show us some code to reproduce the error. And, yes, it's completely safe to create multiple taskflow objects.

**Comment by bsviglo** [comment]
@clin99, @tsung-wei-huang, I've spent some time and found out that the issue is defenetly related to the method
```
template <typename T>
ObjectPool<T>& per_thread_object_pool() {
  thread_local ObjectPool<T> op;
  return op;
}
```
On windows this doesn't work well in case of multi-DLL architecture of an application. So, basically each DLL and EXE have their own copy of `thread_local` variables and this cause undefined behaviour when multiple-DLL try to access those values.

**Comment by PaTiToMaSteR** [comment]
But that’s the normal behavior of DLLs. Every dll has its memory space, they are not shared. You need to override new/delete and fwd to the same memory space, normally the .exe, then execute there malloc or free. So the memory of all dlls are allocated in the same memory space/heap

**Comment by tsung-wei-huang** [comment]
@bsviglo I have made a few changes to the object pool. Would you please sync up with the master branch and try it again?

**Comment by bsviglo** [comment]
@tsung-wei-huang, I've just checked your modifications and unfortunately they didn't help.

I'll try to describe what I did to resolve this issue in the my previous post. The main idea here is to be sure that thread_local variable are defined only once (in my case core.dll) and all other code just use exported function (see CORE_API macro).

Below the same but in more details:

1) create a cpp_taskflow_integration.hpp file with the content (where CORE_API is macros to export/import DLL functions to other users of core.dll (all other modules (exe, dlls) are required to load core.dll)

```
#pragma once

namespace tf
{
class Node;

template <typename T>
class ObjectPool;

template <typename T>
ObjectPool<T>& per_thread_object_pool();

template <>
CORE_API ObjectPool<Node>& per_thread_object_pool<Node>();

} //-- tf
```

2) create cpp_taskflow_integration.cpp file with explicit specialization of per_thread_object_pool() method

```
#include "cpp_taskflow_integration.hpp"
#include <taskflow/taskflow.hpp>

namespace tf
{

template <>
ObjectPool<Node>& per_thread_object_pool<Node>()
{
  thread_local ObjectPool<Node> op;
  return op;
}

} //-- tf
```
3) Removed completely per_thread_object_pool() from object_pool.hpp

cpp_taskflow_integration.hpp is included in every other module and cpp_taskflow_integration.cpp included and compiled only in core.dll.

**Comment by tsung-wei-huang** [comment]
@bsviglo , I have read through many articles about this issue and it seems to me your program is facing large memory allocation rather than leak (plz correct me if you did see leak). I have slightly modified the object pool to limit the reuse size and pushed it to the repo (both dev & master). I don't think removing `thread_local` is the best way to solve the problem for now because being able to reuse the internal task data structure has a significant runtime benefit. Also, the executor has `thread_local` used for scheduling.

But anyway, would you please try it again and let me know if the large memory problem is still there?  If the problem still exists, I will think about some other ways. Thanks!

**Comment by tsung-wei-huang** [comment]
@bsviglo , I removed the `thread_local` and disabled the object pool for now. The current implementation does have some flaws and I am investigating into this. You can sync up with the master branch to see if the problem still exists.

**Comment by bsviglo** [comment]
@tsung-wei-huang, I'll try it tomorrow, but do you tradeoff performance versus conrrectness this time by disabling `thread_local` ?

**Comment by bsviglo** [comment]
@tsung-wei-huang, sorry for the late update. But I've tested my application on the latest version of cpp-taskflow and may confirm that the issue is gone.
Thanks again for the great work!
